---
run_cfg:
  mlflow_server_uri: http://localhost:5000
  mlflow_experiment: sample_experiment
  mlflow_run: sample_run
  seed: 2137
  max_epochs: 30
  swa_start: 25
  swa_anneal: 3
  swa_lr: 0.0001
  early_stopping_patience: 3
  ds_path: data/processed_reviews_poland
  ds_metadata_path: data/processing_metadata_poland
  batch_size: 32
  n_workers: 27
  train_val_split: 0.95

data_loader_cfg:
  use_bert_embeddings: sentence
  word_count_vector_type: tfidf
  use_top_k_words: 4000
  pos_count_vector_type: count_normalized
  use_categorized_features:
    - Meal type
    - Service
    - Price per person
  use_trace_features:
    - [3, 1]
  normalize_trace_features: true

train_cfg:
  classification_classes_weights: [0.09, 0.28, 0.33, 0.28, 0.03]
  reg_loss_weight: null
  translation_cl_loss_weight: null

optimizer_cfg:
  lr: 0.001
  weight_decay: 0.0001

model_cfg:
  bert_encoder:
    input_dim: 1536
    hidden_dims: [512, 256]
    dropout_rate: 0.1
    accepts_sequence: true
  word_count_encoder:
    input_dim: 4000
    hidden_dims: [512, 256]
    dropout_rate: 0.1
    accepts_sequence: false
  pos_count_encoder:
    input_dim: 10
    hidden_dims: [8, 4]
    dropout_rate: 0.1
  cat_features_encoders:
    "Meal type":
      input_dim: 7
      hidden_dim: 3
    "Service":
      input_dim: 5
      hidden_dim: 2
    "Price per person":
      input_dim: 7
      hidden_dim: 3
  supported_trace_features: [trace_cs_3_ss_1]
  num_features_encoder:
    input_dim: 10
    hidden_dims: [8, 4]
    dropout_rate: 0.1
  post_net:
    input_dim: 520
    hidden_dims: [256, 128]
    dropout_rate: 0.1